---
subtitle: "PHIL104Q -- Introduction to Logic"
title: "<font style='font-size:1em;'>🗓️ Week 01/02<br/> Introduction</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "Argument Forms, Formalization, Formation Rules:"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    mouse-wheel: false
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL104Q -- Introduction to Logic'
---

| Unit | Topic | Pages |
|---|---|---|
|1 | What is deductive logic? | 1-8 |
|2 | Validity and soundness | 9-19 |
| 3 | Forms of inference | 20 |

# What is an argument?

::: {.notes}

As I mentioned previously, the most important component of this course, is being able to evaluate arguments for *internal* cogency. There is more than one kind of internal cogency however. Perhaps at a latter time, we will talk about these other kinds of internal cogency, but today and the foreceable future, we will be talking about ***logical validity***. Internal cogency and logical validity are what underlie the kinds "systematic" evaluations of arguments that we will learn about in this course. Once again, there are more than one of these.

## What is an argument?

## Kinds of Evaluation

## Deduction and Induction

## Argument Patterns

# Validity and Soundness

## Defining Validity

## Consistency and Equivalency

## Validity, Invalidity, and Truth

***The Invalidity Principle***

> The only combination ruled out by the definition of validity is a valid inference step’s having all true premisses and yet a false conclusion. Deductive
validity is about the necessary preservation of truth – and therefore a valid
inference step cannot take us from actually true premisses to an actually
false conclusion. [@smit94, 13]

## Inference and Argument

1. Whatever Donald Trump says is true.
2. Donald Trump says that the Flying Spaghetti Monster exists.

So,

3. It is true that the Flying Spaghetti Monster exists.

#### Note three easy consequences of our definition of soundness:

1. any sound argument has a true conclusion;
2. no pair of sound arguments can have conclusions inconsistent with each
other;
3. no sound argument has inconsistent premisses.

Why do these claims hold? For the following reasons:

4. A sound argument starts from true premisses and involves a necessarily truth-preserving inference move – so it must end up with a true
conclusion.
5. Since a pair of sound arguments will have a pair of true conclusions,
this means that the conclusions are true together. If they actually are
true together, then of course they can be true together. And if they
can be true together then (by definition) the conclusions are consistent
with each other.
6. Since inconsistent premisses cannot all be true together, an argument
starting from those premisses cannot satisfy the first of the conditions
for being sound.

## Valid or True

> Despite the common misuse of the terms, resolve to never again say that
a premiss or conclusion or other proposition is ‘valid’ when you mean it is
true. And never again say that an argument is ‘true’ when you mean that
it is valid (or sound). [15]



