---
subtitle: "PHIL104Q -- Logical validity, props and forms, connectives"
title: "<font style='font-size:1em;'>🗓️ Week 04<br/> Informal to Formal Logic</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "MMM DD YYYY"
toc: false
toc-depth: 1
toc-title: "Logical validity, props and forms, connectives"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    scrollable: true
    mouse-wheel: false
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL104Q -- Informal to Formal Logic'
---

# Logical Validity

* logically valid arguments are deductively valid
* but not all deductively valid arguments are logically valid

---

::: {.r-fit-text}

1. Vocabulary such as: 'all' and 'some', 'and' and 'or' and 'if', that does not refer to specific things, properties or relations, are topic-neutral
2. An inference step is logically valid iff it is deductively valid
   * given how the topic-neutral notions occur in the premisses and conclusion
   * ***and*** some premisses logically entail a certain conclusion if the inference from premisses to conclusion is logically valid.
3. A proposition is logically necessary iff it is necessarily true, in virtue of how topic-neutral notions feature in it.
4. We only need to concern ourselves with validity which depends on uncontroversially topic-neutral vocabulary: 'all', 'some', 'and' and 'or' etc.
5. We will accept that our given definitions of validity lead to strange arguments

:::

---


5. We will accept that our given definitions of validity lead to strange arguments

> Jack is married. Jack is not married. So the world will end tomorrow!

The above is logically valid given our definition in 2.1:

* An inference step is *valid* iff there is no possible situation in which its premisses would be true and its conclusion false.

## Topic Neutral Terminology

Vocabulary like 'all' and 'some' and 'or', 'not' and 'if' etc.

* does not refer to specific things, properties or relations,
* useful for discussing any topic (topic neutral)

1. Jill is a mother
2. So, Jill is a parent

1. Anything that is a mother is a parent
2. Jill is a mother
2. So, Jill is a parent

1. Bob is a mother
2. So Bob is a parent

1. Jack has a first cousin
2. So at least one of Jack's parents is not an only child.

1. Jack is a bachelor
2. So Jack is unmarried

## Logical Validity

* Inference step is *logically valid* iff it is deductively valid in virtue of the way that topic-enutral notions occur in the premisses and conclusion
* Some premisses *logically entail* a certain concusaion if th einference from the premisses to the conclusion is logically valid.

---

> How can we show that an unobviously valid inference is logically valid? By
a suitable proof, of course – meaning a proof where the pattern of inference used
at each step can be displayed using a purely logical schema.

---

### E.g.,

* There is something
* Therefore there is not nothing

## Logical Necessity

> Proposition is logically necessarily iff it is necessarily true in virtue of how topic-neutral notions feature in it.

* true in virtue of the meanings of the topic-neutral logical notions
  * whatever
  * is
  * and
* type of proposition which can be specified by a purely logical schema
  * variables and toopic-neutral vocabulary

## The boundaries of logical validity

An argue is logically valid if it is valid in virtue of its topic-neutral form.

## Definitions of validity as rational reconstructions

# Propositions and Forms

## Types vs. Tokens

## Sense vs. Tone

## Are propositions sentences

## Are propositions truth-relevant contents

## Why we can be indecisive

## Forms of inference again

# Connectives

## Two Simple Arguments

## 'And'

## 'Or'

## 'Not'

## Scope

## Formalization

## The design brief for PL languages

## One PL language


