---
title: "Spring 2026 Syllabus"
format:
  html:
    toc: false
    number-sections: true
    colorlinks: true
  pdf:
    documentclass: book
---

| Week | Unit | Topic | Pages |
|---|---|---|---|
| Week 1 |1 | What is deductive logic? | 1-8 |
| |2 | Validity and soundness | 9-19 |
| | 3 | Forms of inference | 20 |
| Week 2 | 4 | Proofs | 28 |
| | 5 | The counterexample method | 39 |
| | 6 | Logical validity | 44 |
| Week 3 | 7 | Propositions and forms | 52 |
| | | Interlude: From informal to formal logic | 59 |
| | 8 | Three connectives | 61 |
| Week 4 | 9 |PL syntax | 72 |
| | 10 | PL semantics | 81 |
| | 11 | ‘P’s, ‘Q’s, ‘α’s, ‘β’s – and form again | 94 |
| Week 5 | 12 | Truth functions | 104 |
| | 13 |Expressive adequacy | 113 |
| | 14 | Tautologies | 120 |
| Week 6 | 15 | Tautological entailment | 127 |
| | 16 More about tautological entailment | 137 |
| | 17 | Explosion and absurdity | 145 |
| Week 7 | 18 | The truth-functional conditional | 148 |
| | 19 | ‘If’s and ‘→’s | 162 |
| | | Interlude: Why natural deduction? | 172 |
| Week 8 | 20 | PL proofs: conjunction and negation | 174 |
| | 21 | PL proofs: disjunction | 191 |
| | 22 | PL proofs: conditionals | 203 |
| Week 9 | 23 | PL proofs: theorems | 211 |
| | 24 | PL proofs: metatheory | 216 |
| | | Interlude: Formalizing general propositions | 228 |
| Week 10 | 25 | Names and predicates | 230 |
| | 26 | Quantifiers in ordinary language |240 |
| | 27 | Quantifier-variable notation | 249 |
| Week 11 | 28 | QL languages | 258 |
| | 29 | Simple translations | 271 |
| | 30 | More on translations | 282 |
| Week 12 || Interlude: Arguing in QL | 290 |
| | 31 | Informal quantifier rules | 293 |
| | 32 | QL proofs | 299 |
| Week 13 | 33 | More QL Proofs | 315 |
| | 34 | Empty Domains | 329 |
| | 35 | Q-Valuations | 333 |
| Week 14 | 36 | Q-Validity | 346 |
| | 37 | QL Proofs, metatheory | 354 |
| | Interlude: Extending QL | 359 |
| Week 15 | 38 | Identity | 361 |
| | 39 | QL=Languages | 367 |
| | 40 | Definite Descriptions | 375 |
| Week 16 | 41 | QL=Proofs | 382 |
| | 42 | Functions | 391 |
| | 42 | Functions | 391 |
| | 42 | Functions | 391 |
