# Study Guide for Wednesday February 11

* Argument: A group of sentential assertions (claims, propositions) is an argument when one or more of these sentences in the group is/are used to give evidence (or if you like, reasons, or grounds) in support of one of the other sentences in the group that is receiving support.
* Conclusion: A sentential assertion that is the part of an argument that is being supported by the premises.
* Deductive Argument: An argument whose premises are claimed to guarantee the truth of its conclusion. Deductive arguments can be either valid or invalid and either sound or unsound.
* Inductive Argument: An argument whose premises are claimed to increase the likelihood that its conclusion is true. Inductive arguments can be weak or strong.
* Logic: The basic principles and techniques that are used in distinguishing correct (good) reasoning from incorrect (bad) reasoning.
* Premise: A sentential assertion that is part of an argument and is used to offer support for the conclusion.
* Sentence: A unit of connected speech or writing that can have various uses, including that of expressing true/false claims.
* Sound Argument: A valid deductive argument all of whose premises are true.
* Valid Argument: A deductive argument whose conclusion would have to be true if its premises were true.
